import "./../globals.css";
import Sidebar from "@/components/menu/Sidebar";
import Navbar from "@/components/menu/Navbar";
import { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayout {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayout) {
  return (
    <div className="flex overflow-hidden w-screen h-screen">
      <Sidebar />
      <div className="flex flex-col flex-1 overflow-hidden">
        <div className="block lg:hidden">
          <Navbar />
        </div>
        <main className="overflow-auto flex-1">{children}</main>
      </div>
    </div>
  );
}
